figure (1); clf;
subplot(2,1,1);
hold on;
plot(t,v(:,1),'b');
plot(t,u_d, '--r');
hold off;
legend('Surge', 'Surge D');
title('Surge');
grid on;
xlabel('time [s]'); 
ylabel('Surge [m/s]');
subplot(2,1,2);
hold on;
plot(t,u_delta);
hold off;
legend('Surge difference');
title('Surge difference');
grid on;
xlabel('time [s]'); 
ylabel('Surge difference [m/s]');


figure (2); clf;
subplot(2,1,1);
hold on;
plot(t, psi, 'r');
hold off;
grid on;
legend('Yaw');
title('Yaw');
xlabel('time [s]'); 
ylabel('Yaw [deg]');
subplot(2,1,2);
hold on;
plot(t,r);
hold off;
grid on;
legend('Yaw Rate');
title('Yaw Rate');
xlabel('time [s]'); 
ylabel('Yaw Rate [deg/s]');

figure (3); clf;
subplot(2,1,1);
hold on;
plot(t,delta_c,'b');
plot(t,25*boundary,'-.r');
plot(t,-25*boundary,'-.r');
hold off;
grid on;
legend('Rudder input','Saturation limits');
title('Rudder input');
xlabel('time [s]'); 
ylabel('Ruder input [deg]');
subplot(2,1,2);
hold on;
plot(t,n_c,'b');
plot(t,85*360/60*boundary,'-.r');
plot(t,-85*360/60*boundary,'-.r');
hold off;
grid on;
legend('Shaft speed','Saturation limits');
title('Shaft speed');
xlabel('time [s]'); 
ylabel('Shaft speed [deg/s]');


hgexport(1,'./Figures/SurgeAutoPilot/SurgeAutoPilot');
hgexport(2,'./Figures/SurgeAutoPilot/YawAndYawRateSurgeAutoPilot');
hgexport(3,'./Figures/SurgeAutoPilot/Delta_cAndShaftSurgeAutoPilot');